import { z } from 'zod';

export const plantSchema = z.object({
  id: z.number(),
  common_name: z.string(),
  scientific_name: z.array(z.string()),
  other_name: z.array(z.string()),
  family: z.string(),
  origin: z.array(z.string()),
  type: z.string(),
  dimension: z.string(),
  dimensions: z.object({
    type: z.string(),
    min_value: z.number(),
    max_value: z.number(),
    unit: z.string()
  }),
  cycle: z.string(),
  attracts: z.array(z.string()),
  propagation: z.array(z.string()),
  hardiness: z.object({ min: z.string(), max: z.string() }),
  hardiness_location: z.object({
    full_url: z.string(),
    full_iframe: z.string()
  }),
  watering: z.string(),
  depth_water_requirement: z.array(z.string()),
  volume_water_requirement: z.array(z.string()),
  watering_period: z.unknown(),
  watering_general_benchmark: z.object({ value: z.string(), unit: z.string() }),
  plant_anatomy: z.array(z.object({})),
  sunlight: z.array(z.string()),
  pruning_month: z.array(z.string()),
  pruning_count: z.array(z.string()),
  seeds: z.number(),
  maintenance: z.string(),
  'care-guides': z.string(),
  soil: z.array(z.string()),
  growth_rate: z.string(),
  drought_tolerant: z.boolean(),
  salt_tolerant: z.boolean(),
  thorny: z.boolean(),
  invasive: z.boolean(),
  tropical: z.boolean(),
  indoor: z.boolean(),
  care_level: z.string(),
  pest_susceptibility: z.array(z.string()),
  pest_susceptibility_api: z.string(),
  flowers: z.boolean(),
  flowering_season: z.unknown(),
  flower_color: z.string(),
  cones: z.boolean(),
  fruits: z.boolean(),
  edible_fruit: z.boolean(),
  edible_fruit_taste_profile: z.string(),
  fruit_nutritional_value: z.string(),
  fruit_color: z.array(z.string()),
  harvest_season: z.unknown(),
  leaf: z.boolean(),
  leaf_color: z.array(z.string()),
  edible_leaf: z.boolean(),
  cuisine: z.boolean(),
  medicinal: z.boolean(),
  poisonous_to_humans: z.number(),
  poisonous_to_pets: z.number(),
  description: z.string(),
  default_image: z.object({
    license: z.number(),
    license_name: z.string(),
    license_url: z.string(),
    original_url: z.string(),
    regular_url: z.string(),
    medium_url: z.string(),
    small_url: z.string(),
    thumbnail: z.string()
  })
});

export type plantType = z.infer<typeof plantSchema>;